version: "3.7"

services:
  server:
    build:
      context: "."
      target: base
    environment:
      DATABASE_URL: $$DATABASE_URL
    ports:
      - 9999:80
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
    networks:
      - test_vm

volumes:
  database:
networks:
  test_vm:
