name: Test

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
      - run: npx prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - run: npm run migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - run: npm run test
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
