name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Spin up test environment
        run: |
          docker-compose -f docker-compose.test.yml build
      - name: Build database
        run: |
          docker-compose -f docker-compose.test.yml run --rm server npx prisma migrate reset --force test && npx prisma migrate dev --name test --force
      - name: Run tests
        run: |
          docker-compose -f docker-compose.test.yml run --rm server yarn jest -i
        continue-on-error: true
